
m = {
    'DE': 'GERMANY', 'HU': 'HUNGARY', 'CZ': 'CZECH REPUBLIC', 'SK': 'SLOVAKIA',
    'XS': 'GERMANY', 'PL': 'POLAND', 'FR': 'FRANCE', 'IT': 'ITALY', 'ES': 'SPAIN',
    'PT': 'PORTUGAL', 'NL': 'NETHERLANDS', 'BE': 'BELGIUM', 'AT': 'AUSTRIA',
    'CH': 'SWITZERLAND', 'SE': 'SWEDEN', 'NO': 'NORWAY', 'DK': 'DENMARK',
    'FI': 'FINLAND', 'IE': 'IRELAND', 'GB': 'UNITED KINGDOM', 'UK': 'UNITED KINGDOM',
    'RO': 'ROMANIA', 'BG': 'BULGARIA', 'HR': 'CROATIA', 'SI': 'SLOVENIA',
    'RS': 'SERBIA', 'BA': 'BOSNIA AND HERZEGOVINA', 'ME': 'MONTENEGRO',
    'MK': 'NORTH MACEDONIA', 'AL': 'ALBANIA', 'LT': 'LITHUANIA',
    'LV': 'LATVIA', 'EE': 'ESTONIA', 'LU': 'LUXEMBOURG', 'MT': 'MALTA',
    'CY': 'CYPRUS', 'GR': 'GREECE', 'IS': 'ICELAND', 'UA': 'UKRAINE',
    'BY': 'BELARUS', 'MD': 'MOLDOVA', 'RU': 'RUSSIA',
    'CN': 'CHINA', 'IN': 'INDIA', 'JP': 'JAPAN', 'KR': 'SOUTH KOREA',
    'TW': 'TAIWAN, PROVINCE OF CHINA', 'TH': 'THAILAND', 'VN': 'VIETNAM', 'MY': 'MALAYSIA',
    'SG': 'SINGAPORE', 'ID': 'INDONESIA', 'PH': 'PHILIPPINES', 'BD': 'BANGLADESH',
    'PK': 'PAKISTAN', 'LK': 'SRI LANKA', 'NP': 'NEPAL', 'MM': 'MYANMAR',
    'KH': 'CAMBODIA', 'LA': 'LAOS', 'MN': 'MONGOLIA', 'KZ': 'KAZAKHSTAN',
    'UZ': 'UZBEKISTAN', 'AF': 'AFGHANISTAN',
    'AE': 'UNITED ARAB EMIRATES', 'SA': 'SAUDI ARABIA', 'QA': 'QATAR',
    'KW': 'KUWAIT', 'BH': 'BAHRAIN', 'OM': 'OMAN', 'IR': 'IRAN',
    'IQ': 'IRAQ', 'IL': 'ISRAEL', 'JO': 'JORDAN', 'LB': 'LEBANON',
    'TR': 'TURKEY', 'GE': 'GEORGIA', 'AM': 'ARMENIA', 'AZ': 'AZERBAIJAN',
    'US': 'UNITED STATES', 'CA': 'CANADA', 'MX': 'MEXICO',
    'BR': 'BRAZIL', 'AR': 'ARGENTINA', 'CL': 'CHILE', 'CO': 'COLOMBIA',
    'PE': 'PERU', 'VE': 'VENEZUELA', 'EC': 'ECUADOR', 'UY': 'URUGUAY',
    'PY': 'PARAGUAY', 'BO': 'BOLIVIA', 'CR': 'COSTA RICA', 'PA': 'PANAMA',
    'DO': 'DOMINICAN REPUBLIC', 'GT': 'GUATEMALA', 'CU': 'CUBA',
    'HN': 'HONDURAS', 'SV': 'EL SALVADOR', 'NI': 'NICARAGUA',
    'ZA': 'SOUTH AFRICA', 'EG': 'EGYPT', 'NG': 'NIGERIA', 'KE': 'KENYA',
    'MA': 'MOROCCO', 'TN': 'TUNISIA', 'GH': 'GHANA', 'ET': 'ETHIOPIA',
    'TZ': 'TANZANIA', 'DZ': 'ALGERIA', 'LY': 'LIBYA',
    'AU': 'AUSTRALIA', 'NZ': 'NEW ZEALAND',
}

user_map = {
    "SK": "Slovakia",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "TR": "Turkey",
    "HU": "Hungary",
    "JP": "Japan",
    "PT": "Portugal",
    "RO": "Romania",
    "ES": "Spain",
    "IT": "Italy",
    "FR": "France",
    "PL": "Poland",
    "AT": "Austria",
    "BE": "Belgium",
    "NL": "Netherlands",
    "SE": "Sweden",
    "GB": "United Kingdom",
    "CN": "China",
    "KR": "South Korea",
    "US": "United States",
    "MX": "Mexico",
    "BR": "Brazil",
    "IN": "India",
    "TH": "Thailand",
    "SI": "Slovenia",
    "RS": "Serbia",
    "BA": "Bosnia and Herzegovina",
    "HR": "Croatia",
    "BG": "Bulgaria",
    "TW": "Taiwan",
    "MY": "Malaysia",
    "ID": "Indonesia",
    "ZA": "South Africa",
    "FI": "Finland",
    "DK": "Denmark",
    "NO": "Norway",
    "CH": "Switzerland",
    "IE": "Ireland",
    "LU": "Luxembourg",
}

missing = []
for code, name in user_map.items():
    if code not in m:
        missing.append((code, name))

print("Missing in m:")
print(missing)
